global_options:

  freezed:freezed:
    runs_before:
      - hive_generator:hive_generator
targets:
  $default:
    builders:
      source_gen:combining_builder:
        options:
          ignore_for_file:
          - library_private_types_in_public_api
          - non_constant_identifier_names